
language: java

env:
  global:
    - TMPDIR=/tmp
    
addons:
  apt:
    packages:
      - libwww-perl
jdk:
  - oraclejdk8

python:
 - 2.7

before_install:
  - if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ] ; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get -qq update && sudo apt-get -qq install g++-4.8 gcc-4.8 && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90 && sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90 ; fi

  
install:
  - echo " .... Installing JPF ..... "
  - export JPF_TRAVIS=$(pwd)/jpf-travis
  - mkdir -p $JPF_TRAVIS
  - wget --output-document=jpf-travis.tar.gz https://www.dropbox.com/s/vjqfokrldjv0mro/jpf-travis.tar.gz?dl=1;
  - tar xvf jpf-travis.tar.gz --strip-components=1 -C $JPF_TRAVIS;
  - ls $JPF_TRAVIS
  - cd $JPF_TRAVIS
  - export JPF_CORE=$(pwd)/jpf-core
  - mkdir -p $JPF_CORE
  - tar xvf jpf-core.tar.gz --strip-components=1 -C $JPF_CORE;
  - mv .jpf $TRAVIS_BUILD_DIR
  - cd ../
  - pwd
  - ls .jpf
  - echo ".... Installing JAYHORN .... "
  - git clone https://github.com/jayhorn/jayhorn
  - ls
  - cd jayhorn
  - ls
  - git checkout devel
  - cd jayhorn
  - ls
  - ./gradlew jar
  - ls build/libs/
  - cd ../..
  - java -jar jayhorn/jayhorn/build/libs/jayhorn.jar -h
  - echo ".... Installing CBMC .... "
  - export CBMC="$TRAVIS_BUILD_DIR/../cbmc"
  - git clone https://github.com/coco-team/zustre $CBMC
  - ls $CBMC
  - cd $CBMC
  - cd src
  - make minisat2-download
  - make
  - cd
  - ls

before_install:
   - echo "Running the experiments."
   - pwd
   - export LD_LIBRARY_PATH=$(pwd)/jayhorn/jayhorn/native_lib

script:   
   - echo "    RUNNING  CBMC    " 
   - python runner.py ./benchmarks/cbmc-java
   - echo "    RUNNING  MinePUMP    " 
   - python runner.py ./benchmarks/MinePump/spec1-5

after_success:
   - echo "All done."
