
language: java

sudo: required

env:
  global:
    - TMPDIR=/tmp
    
addons:
  apt:
    packages:
      - libwww-perl

compiler:
  - gcc
  - clang
  
jdk:
  - oraclejdk8

python:
 - 2.7

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - until sudo apt-get -qq install g++-4.8 gcc-4.8; done
  - until sudo apt-get -qq install libstdc++-4.8-dev; do echo retry; done
  
  
before_install:
   - pwd
   - export LD_LIBRARY_PATH=$(pwd)/jayhorn/jayhorn/native_lib

  
install:
  - echo ".... Installing JAYHORN .... "
  - git clone https://github.com/jayhorn/jayhorn
  - ls
  - cd jayhorn
  - ls
  - git checkout devel
  - cd jayhorn
  - ls
  - ./gradlew jar
  - ls build/libs/
  - cd ../..
  - java -jar jayhorn/jayhorn/build/libs/jayhorn.jar -h
  - echo ".... Installing CBMC .... "
  - export CBMC="$TRAVIS_BUILD_DIR/../cbmc"
  - git clone https://github.com/diffblue/cbmc $CBMC
  - ls $CBMC
  - cd $CBMC
  - ls
  - cd src
  - ls
  - make minisat2-download
  - make CXX="g++-4.8" CXXFLAGS="-Wall -O2 -g -Werror -Wno-deprecated-register -pedantic -Wno-sign-compare" -j2
  - ./cbmc/cbmc -h
  - pwd
  - cd
  - ls

script:   
   - echo "    RUNNING  CBMC    " 
   - echo "    RUNNING  MinePUMP    " 
   

after_success:
   - echo "All done."
